In [37]:
import pandas as pd

filepath = 'epc_postcodefull.csv'

df = pd.read_csv(filepath, low_memory=False)
df.columns

Index(['key', 'add1', 'add2', 'add3', 'pcode', 'bref', 'curr_enr', 'poten_enr',
       'prop_type', 'builtform', 'insp_date', 'localauth_code', 'constit_code',
       'transact_type', 'curr_encons', 'poten_encons', 'curr_co2',
       'curr_co2perarea', 'poten_co2', 'tfa', 'mainsgas', 'flvl', 'flattop',
       'flattop_cnt', 'mainheatcontrol', 'glaze_percent', 'glaze_type',
       'glaze_area', 'nextension', 'nrooms', 'nheatedrooms', 'led_percent',
       'nfireplace', 'hotwtr', 'hotwtr_eff', 'floor', 'floor_eff', 'window',
       'window_eff', 'wall', 'wall_eff', 'heat2', 'heat2_eff', 'roof',
       'roof_eff', 'heat', 'heat_eff', 'control', 'control_eff', 'light',
       'light_eff', 'mainfuel', 'windt', 'fheight', 'pv', 'solarwtr',
       'mechvent', 'gascons', 'gasmeters', 'gasavg', 'gasmid', 'gasmatch',
       'eleccons', 'elecmeters', 'elecavg', 'elecmid', 'elecmatch'],
      dtype='object')

In [38]:
df = df[(df.gasmatch.str.contains('exact')) & (df.elecmatch.str.contains('exact'))]

In [39]:
temp = df[['add1',
           'add2', 
           'add3', 
           'pcode', 
           'bref', 
           'curr_enr',
           'prop_type', 
           'builtform', 
           'insp_date', 
           'localauth_code',
           'transact_type', 
           'curr_encons',
           'tfa', 
           'mainsgas',
           'nrooms',
           'wall',
           'gascons', 
           'gasmeters', 
           'gasavg', 
           'gasmid', 
           'eleccons', 
           'elecmeters', 
           'elecavg', 
           'elecmid']]

In [40]:
temp.head()

,add1,add2,add3,pcode,bref,curr_enr,prop_type,builtform,insp_date,localauth_code,...,nrooms,wall,gascons,gasmeters,gasavg,gasmid,eleccons,elecmeters,elecavg,elecmid
0,"Apartment 73, Globe View","10, High Timber Street",NaN,EC4V 3PQ,6648304468,B,Flat,Enclosed End-Terrace,2008-01-04,E09000001,...,3,"System built, as built, insulated (assumed)",44272.007913,8,5534.0009891,3274.975272,44841.2,11,4076.4727273,3173.2
1,Apartment 75 Globe View,"10, High Timber Street",NaN,EC4V 3PQ,7191803668,B,Flat,Mid-Terrace,2009-06-09,E09000001,...,3,"System built, as built, insulated (assumed)",44272.007913,8,5534.0009891,3274.975272,44841.2,11,4076.4727273,3173.2
2,Apartment 74 Globe View,"10, High Timber Street",NaN,EC4V 3PQ,1185564668,B,Flat,Detached,2009-07-09,E09000001,...,3,"Timber frame, as built, insulated (assumed)",44272.007913,8,5534.0009891,3274.975272,44841.2,11,4076.4727273,3173.2
3,Apartment 77 Globe View,"10, High Timber Street",NaN,EC4V 3PQ,631555768,B,Flat,End-Terrace,2010-05-04,E09000001,...,3,"Cavity wall, as built, insulated (assumed)",44272.007913,8,5534.0009891,3274.975272,44841.2,11,4076.4727273,3173.2
4,Apartment 78 Globe View,"10, High Timber Street",NaN,EC4V 3PQ,7217676768,B,Flat,Mid-Terrace,2010-06-03,E09000001,...,3,"Cavity wall, as built, insulated (assumed)",44272.007913,8,5534.0009891,3274.975272,44841.2,11,4076.4727273,3173.2

In [41]:
temp.to_csv('epcshort_postcodefull.csv', index=False)