In [71]:
import pandas as pd

filepath1 = 'https://raw.githubusercontent.com/LondonEnergyMap/rawdata/master/consumption/gasUK2015.csv'
filepath2 = 'https://raw.githubusercontent.com/LondonEnergyMap/rawdata/master/consumption/elecUK2015.csv'

dfgas = pd.read_csv(filepath1)

In [72]:
dfgas.head()

,Local Authority Name,Local Authority Code,LSOA Name,Lower Layer Super Output Area (LSOA) Code,Consumption (kWh),Number of meters,Mean consumption (kWh per meter),Median consumption (kWh per meter)
0,Hartlepool,E06000001,Hartlepool 001A,E01011954,11661918.89,969,12035.00401,11217.61
1,Hartlepool,E06000001,Hartlepool 001B,E01011969,8598991.49,631,13627.56179,13083.09
2,Hartlepool,E06000001,Hartlepool 001C,E01011970,6187091.99,454,13627.95593,13208.7
3,Hartlepool,E06000001,Hartlepool 001D,E01011971,7389273,530,13942.02453,13435.21
4,Hartlepool,E06000001,Hartlepool 001F,E01033465,11333577.65,808,14026.70501,13522.26

In [73]:
dfgas.columns=['la' ,'lacode', 'lsoa', 'lsoacode', 'gas', 'gasmeters', 'gasmean', 'gasmid']

In [74]:
ldnpath = 'https://raw.githubusercontent.com/LondonEnergyMap/rawdata/master/boroughsldn_lookup/localauthority_lookuptable.csv'

dfldn = pd.read_csv(ldnpath)

In [75]:
boroughs = dfldn.localauthority[dfldn.london==1]
boroughs

0             City of London
2       Barking and Dagenham
5                     Barnet
6                     Bexley
9                      Brent
10                   Bromley
13                    Camden
14                   Croydon
17                    Ealing
18                   Enfield
21                 Greenwich
22                   Hackney
25    Hammersmith and Fulham
26                  Haringey
29                    Harrow
30                  Havering
34                  Hounslow
38    Kensington and Chelsea
41      Kingston upon Thames
42                   Lambeth
45                  Lewisham
46                    Merton
49                    Newham
50                 Redbridge
53      Richmond upon Thames
54                 Southwark
57                    Sutton
58             Tower Hamlets
61            Waltham Forest
62                Wandsworth
65               Westminster
Name: localauthority, dtype: object

In [76]:
dfgas_ldn = dfgas[dfgas.la.isin(boroughs)]

In [77]:
dfgas_ldn.head()

,la,lacode,lsoa,lsoacode,gas,gasmeters,gasmean,gasmid
28015,Barking and Dagenham,E09000002,Barking and Dagenham 001A,E01000027,7328749.24,641,11433.30615,10486.65
28016,Barking and Dagenham,E09000002,Barking and Dagenham 001B,E01000028,5571294.76,601,9270.041198,8466.86
28017,Barking and Dagenham,E09000002,Barking and Dagenham 001C,E01000029,8176398.62,607,13470.17895,12884.27
28018,Barking and Dagenham,E09000002,Barking and Dagenham 001D,E01000030,6804284.64,709,9597.016417,8921.86
28019,Barking and Dagenham,E09000002,Barking and Dagenham 002A,E01000031,8628396.31,567,15217.63018,14126.61

In [78]:
dfgas_ldn[dfgas_ldn.gas.str.contains('-')]

,la,lacode,lsoa,lsoacode,gas,gasmeters,gasmean,gasmid
29724,Greenwich,E09000011,Greenwich 036D,E01033732,-,-,-,-
29725,Greenwich,E09000011,Greenwich 036E,E01033733,-,-,-,-
29982,Hammersmith and Fulham,E09000013,Hammersmith and Fulham 023E,E01032789,-,-,-,-
31066,Lambeth,E09000022,Lambeth 004G,E01033208,-,-,-,-
31666,Newham,E09000025,Newham 034F,E01033574,-,-,-,-
31667,Newham,E09000025,Newham 034G,E01033575,-,-,-,-
32372,Tower Hamlets,E09000030,Tower Hamlets 028H,E01032779,-,-,-,-
32387,Tower Hamlets,E09000030,Tower Hamlets 032D,E01032773,-,-,-,-

In [79]:
# dfgas_ldn.to_csv('gasldn2015.csv', index=False)

In [80]:
dfelec = pd.read_csv(filepath2)
dfelec.columns=['la' ,'lacode', 'lsoa', 'lsoacode', 'elec', 'elecmeters', 'elecmean', 'elecmid']
dfelec_ldn = dfelec[dfelec.la.isin(boroughs)]
# dfelec_ldn.to_csv('elecldn2015.csv', index=False)

In [81]:
dfelec.head()

,la,lacode,lsoa,lsoacode,elec,elecmeters,elecmean,elecmid
0,Hartlepool,E06000001,Hartlepool 001A,E01011954,2969069.3,967,3070.392244,2609.2
1,Hartlepool,E06000001,Hartlepool 001B,E01011969,2039030.1,640,3185.984531,2864.3
2,Hartlepool,E06000001,Hartlepool 001C,E01011970,1621503.9,453,3579.478808,3230.9
3,Hartlepool,E06000001,Hartlepool 001D,E01011971,2111305.5,530,3983.595283,3460.05
4,Hartlepool,E06000001,Hartlepool 001F,E01033465,2906157.53,827,3514.096167,3133.5

In [82]:
dfelec_ldn[dfelec_ldn.elec.str.contains('-')]

Empty DataFrame
Columns: [la, lacode, lsoa, lsoacode, elec, elecmeters, elecmean, elecmid]
Index: []

In [83]:
gaspath = 'https://media.githubusercontent.com/media/LondonEnergyMap/cleandata/master/consumption/gasldn2015.csv'
elecpath = 'https://media.githubusercontent.com/media/LondonEnergyMap/cleandata/master/consumption/elecldn2015.csv'

dfgasldn = pd.read_csv(gaspath)
dfelecldn = pd.read_csv(elecpath)

In [84]:
dfgasldn.head()
dfgasldn[dfgasldn.gas.str.contains('-')]

,la,lacode,lsoa,lsoacode,gas,gasmeters,gasmean,gasmid
1709,Greenwich,E09000011,Greenwich 036D,E01033732,-,-,-,-
1710,Greenwich,E09000011,Greenwich 036E,E01033733,-,-,-,-
1967,Hammersmith and Fulham,E09000013,Hammersmith and Fulham 023E,E01032789,-,-,-,-
2630,Lambeth,E09000022,Lambeth 004G,E01033208,-,-,-,-
3230,Newham,E09000025,Newham 034F,E01033574,-,-,-,-
3231,Newham,E09000025,Newham 034G,E01033575,-,-,-,-
3936,Tower Hamlets,E09000030,Tower Hamlets 028H,E01032779,-,-,-,-
3951,Tower Hamlets,E09000030,Tower Hamlets 032D,E01032773,-,-,-,-

In [85]:
dfgasldn['gas'] = pd.to_numeric(dfgasldn.gas, errors='coerce')

In [86]:
dfgasldn.groupby(['la']).sum()[['gas']]

# compared to sub-national statistics, 
# the boroughs with missing values did not give lower total consumption
# this suggests that the data is simply missing

                                 gas
la
Barking and Dagenham    7.336931e+08
Barnet                  2.171469e+09
Bexley                  1.242413e+09
Brent                   1.532682e+09
Bromley                 2.060456e+09
Camden                  9.545412e+08
Croydon                 2.057868e+09
Ealing                  1.657614e+09
Enfield                 1.545759e+09
Greenwich               1.134603e+09
Hackney                 9.651015e+08
Hammersmith and Fulham  8.740235e+08
Haringey                1.262622e+09
Havering                1.336480e+09
Hounslow                1.150508e+09
Kensington and Chelsea  8.703268e+08
Kingston upon Thames    8.960422e+08
Lambeth                 1.386326e+09
Lewisham                1.334017e+09
Merton                  1.071768e+09
Newham                  1.082918e+09
Redbridge               1.428750e+09
Richmond upon Thames    1.181227e+09
Southwark               1.039574e+09
Sutton                  1.048335e+09
Tower Hamlets           7.016702e+08
Waltham Forest          1.196596e+09
Wandsworth              1.518386e+09
Westminster             9.661135e+08

In [95]:
# sort by lsoa code then interpolate missing values using nearest value


temp = dfgasldn.sort_values(by='lsoa')
temp['gas'] = temp.gas.interpolate(method='nearest')
temp.gas.isnull().values.any()

False

In [96]:
temp[temp.lacode.str.contains('E09000011')]

,la,lacode,lsoa,lsoacode,gas,gasmeters,gasmean,gasmid
1569,Greenwich,E09000011,Greenwich 001A,E01001690,5637503.61,624,9034.460913,8157
1570,Greenwich,E09000011,Greenwich 001B,E01001692,4595351.29,557,8250.181849,7435.9
1571,Greenwich,E09000011,Greenwich 001C,E01001693,4956453.69,626,7917.657652,7116.37
1572,Greenwich,E09000011,Greenwich 001D,E01001694,5703621.71,617,9244.119465,8383
1573,Greenwich,E09000011,Greenwich 002A,E01001687,3546044.88,453,7827.913642,7308.68
1574,Greenwich,E09000011,Greenwich 002B,E01001688,7491001.57,789,9494.298568,8663.71
1575,Greenwich,E09000011,Greenwich 002E,E01033739,5556187.38,648,8574.363241,7545.86
1576,Greenwich,E09000011,Greenwich 002F,E01033740,4957279.15,514,9644.511965,9103.06
1577,Greenwich,E09000011,Greenwich 002G,E01033741,6014854.63,457,13161.60751,11811.64
1578,Greenwich,E09000011,Greenwich 002H,E01033743,6105517.75,518,11786.7138,11138.07
1579,Greenwich,E09000011,Greenwich 002I,E01033745,5828753.80,574,10154.62334,9655.82
1580,Greenwich,E09000011,Greenwich 003A,E01001575,6254161.14,625,10006.65782,9569
1581,Greenwich,E09000011,Greenwich 003B,E01001576,6388530.44,685,9326.32181,8586
1582,Greenwich,E09000011,Greenwich 003C,E01001577,6634576.25,730,9088.460616,8745.5
1583,Greenwich,E09000011,Greenwich 003D,E01001578,7827250.13,705,11102.48245,9817
1584,Greenwich,E09000011,Greenwich 003E,E01001579,6632130.34,658,10079.22544,9274
1585,Greenwich,E09000011,Greenwich 004B,E01001709,4840086.79,448,10803.76516,8631.57
1586,Greenwich,E09000011,Greenwich 004C,E01001711,2531395.70,251,10085.24183,9900.39
1587,Greenwich,E09000011,Greenwich 004D,E01001712,4288805.35,624,6873.085497,6246.5
1588,Greenwich,E09000011,Greenwich 004E,E01033731,1386613.97,99,14006.20172,8750
1589,Greenwich,E09000011,Greenwich 004F,E01033734,1943781.07,137,14188.18299,13256.41
1590,Greenwich,E09000011,Greenwich 004G,E01033735,853705.31,60,14228.42183,9430.5
1591,Greenwich,E09000011,Greenwich 004H,E01033736,2916358.97,348,8380.341868,7184.42
1592,Greenwich,E09000011,Greenwich 004I,E01033737,5726849.57,543,10546.68429,9152
1593,Greenwich,E09000011,Greenwich 005A,E01001705,6162221.87,573,10754.31391,9651
1594,Greenwich,E09000011,Greenwich 005B,E01001706,5276313.83,498,10595.00769,9607.5
1595,Greenwich,E09000011,Greenwich 005C,E01001708,8724654.55,652,13381.37201,11584
1596,Greenwich,E09000011,Greenwich 005D,E01001710,5451811.22,629,8667.426423,8033
1597,Greenwich,E09000011,Greenwich 005E,E01001713,4229713.87,458,9235.183122,8048.5
1598,Greenwich,E09000011,Greenwich 006A,E01001672,7308161.30,625,11693.05808,10917
...,...,...,...,...,...,...,...,...
1690,Greenwich,E09000011,Greenwich 032B,E01001599,10614902.37,625,16983.84379,16247
1691,Greenwich,E09000011,Greenwich 032C,E01001600,9530869.76,632,15080.49013,14482.5
1692,Greenwich,E09000011,Greenwich 032D,E01001601,9493127.22,554,17135.6087,17018.92
1693,Greenwich,E09000011,Greenwich 033A,E01001669,9124673.87,797,11448.77524,10336
1694,Greenwich,E09000011,Greenwich 033B,E01001671,8206437.72,725,11319.22444,10675
1695,Greenwich,E09000011,Greenwich 033C,E01001676,7066095.86,636,11110.21362,9686
1696,Greenwich,E09000011,Greenwich 033D,E01032567,8126414.33,590,13773.58361,12695
1697,Greenwich,E09000011,Greenwich 034A,E01001656,8255112.18,600,13758.5203,11789.5
1698,Greenwich,E09000011,Greenwich 034B,E01001657,10916283.99,684,15959.47952,11995.5
1699,Greenwich,E09000011,Greenwich 034C,E01001658,8278975.19,743,11142.63148,9869
1700,Greenwich,E09000011,Greenwich 034D,E01001659,10532193.74,528,19947.33663,19186.5
1701,Greenwich,E09000011,Greenwich 034E,E01033726,10026835.81,805,12455.69666,12004
1702,Greenwich,E09000011,Greenwich 035A,E01001640,7520034.13,892,8430.531536,7215
1703,Greenwich,E09000011,Greenwich 035B,E01033727,5256277.48,546,9626.881832,8538.5
1704,Greenwich,E09000011,Greenwich 035C,E01033728,1136744.58,70,16239.20829,14796.84
1705,Greenwich,E09000011,Greenwich 035D,E01033730,4215186.97,608,6932.873306,5253.37
1706,Greenwich,E09000011,Greenwich 036A,E01001666,6978772.69,567,12308.24108,11153
1707,Greenwich,E09000011,Greenwich 036B,E01001667,5837069.96,615,9491.170667,8917
1708,Greenwich,E09000011,Greenwich 036C,E01001668,7298813.83,717,10179.65667,9573
1709,Greenwich,E09000011,Greenwich 036D,E01033732,7298813.83,-,-,-
1710,Greenwich,E09000011,Greenwich 036E,E01033733,9584488.27,-,-,-
1711,Greenwich,E09000011,Greenwich 037A,E01001662,9584488.27,875,10953.70088,10012
1712,Greenwich,E09000011,Greenwich 037B,E01001664,9393868.21,814,11540.37864,9980.2
1713,Greenwich,E09000011,Greenwich 037C,E01001665,8060823.06,612,13171.27951,12150
1714,Greenwich,E09000011,Greenwich 037D,E01033738,8536094.89,777,10985.96511,9121
1715,Greenwich,E09000011,Greenwich 038A,E01001638,5727213.68,660,8677.596485,7810.5
1716,Greenwich,E09000011,Greenwich 038B,E01001641,9752851.54,786,12408.20807,9905
1717,Greenwich,E09000011,Greenwich 038C,E01001642,12544123.16,780,16082.20918,13349.21
1718,Greenwich,E09000011,Greenwich 038D,E01001644,10546166.82,971,10861.13988,8479
1719,Greenwich,E09000011,Greenwich 038E,E01033746,7384146.63,620,11909.91392,11210